--Programmers 301651
WITH RECURSIVE CTE AS
(
SELECT ID, PARENT_ID, 1 AS LEVEL
FROM ECOLI_DATA
WHERE PARENT_ID IS NULL
UNION ALL
SELECT A.ID, A.PARENT_ID, B.LEVEL+1 AS LEVEL
FROM ECOLI_DATA A
INNER JOIN CTE B
ON A.PARENT_ID = B.ID)

SELECT COUNT(*) AS COUNT, LEVEL AS GENERATION
FROM CTE
WHERE NOT EXISTS (SELECT 1
                FROM ECOLI_DATA
                WHERE PARENT_ID=CTE.ID)
GROUP BY LEVEL
ORDER BY GENERATION