/* Programmers 62284 */
SELECT A.CART_ID
FROM (SELECT * FROM CART_PRODUCTS WHERE NAME='Milk') A
JOIN (SELECT * FROM CART_PRODUCTS WHERE NAME='Yogurt') B
ON A.CART_ID=B.CART_ID
GROUP BY CART_ID
ORDER BY CART_ID