/* Programmers 131124 */
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') REVIEW_DATE
FROM REST_REVIEW R INNER JOIN (SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(*) DESC
LIMIT 1) R_I
ON R.MEMBER_ID=R_I.MEMBER_ID
JOIN MEMBER_PROFILE M
ON M.MEMBER_ID=R.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT