/* Programmers 131532 */
SELECT YEAR(SALES_DATE) YEAR ,MONTH(SALES_DATE) MONTH,GENDER, COUNT(*) USERS
FROM (SELECT SALES_DATE, YEAR(SALES_DATE) YEAR ,MONTH(SALES_DATE) MONTH,GENDER, COUNT(*) USERS
FROM USER_INFO U JOIN ONLINE_SALE O
ON U.USER_ID=O.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR,MONTH,GENDER,U.USER_ID) A
GROUP BY A.YEAR,A.MONTH,A.GENDER
ORDER BY A.YEAR,A.MONTH,A.GENDER