/* Programmers 133027 */
SELECT F.FLAVOR
FROM FIRST_HALF F JOIN
(SELECT *,SUM(TOTAL_ORDER) AS T_O
 FROM JULY
GROUP BY FLAVOR) J
ON F.SHIPMENT_ID=J.SHIPMENT_ID
ORDER BY F.TOTAL_ORDER+J.T_O DESC
LIMIT 3