-- Programmers 276035
SELECT DISTINCT(ID), EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D
WHERE SKILL_CODE & (SELECT SUM(CODE)
                   FROM SKILLCODES
                   GROUP BY CATEGORY
                   HAVING CATEGORY='Front End')
ORDER BY ID