--Programmers 276036
WITH DEV_SKILL AS (
    SELECT ID, GROUP_CONCAT(NAME) AS NAME, GROUP_CONCAT(CATEGORY) AS CATEGORY
    FROM DEVELOPERS D
    JOIN SKILLCODES S ON D.SKILL_CODE & S.CODE = S.CODE
    GROUP BY ID
)

SELECT CASE WHEN CATEGORY LIKE '%Front End%' AND NAME LIKE '%Python%' THEN 'A'
WHEN NAME LIKE '%C#%' THEN 'B'
WHEN CATEGORY LIKE '%Front End%' THEN 'C' END GRADE,
DS.ID, EMAIL
FROM DEV_SKILL DS JOIN DEVELOPERS D
ON DS.ID=D.ID
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID